// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckMate.Data.Context;

#nullable disable

namespace TruckMate.Migrations
{
    [DbContext(typeof(TruckMateDbContext))]
    [Migration("20260508155017_AddDriverWalletEarnings")]
    partial class AddDriverWalletEarnings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TruckMate.Core.Models.CourierShipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CargoType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("bit");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeightLbs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.ToTable("CourierShipments");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DeliveryTrip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AssignedDriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DistanceKm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<decimal>("EarningsOnCompletionEgp")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EstimatedDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("OfferedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaymentAmountEGP")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ScheduleStatus")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<TimeSpan?>("ScheduledStartTime")
                        .HasColumnType("time");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ShipmentNumericId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TraderId")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDriverId");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("TraderId");

                    b.HasIndex("Zone");

                    b.ToTable("DeliveryTrips");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AssignedDeliveryTripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailabilityStatus")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<string>("CurrentZone")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("LastAvailabilityChangeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("TruckType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDeliveryTripId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DriverPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("DriverPublicId");

                    b.ToTable("DriverAuditLogs");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverDailySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal>("EarningsEGP")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OnlineTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date");

                    b.Property<int>("TripsCompleted")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "SummaryDate")
                        .IsUnique();

                    b.ToTable("DriverDailySummaries");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverEarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AmountEGP")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DropoffLocation")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.HasIndex("DriverId", "EarnedAt")
                        .IsDescending(false, true);

                    b.HasIndex("DriverId", "Status");

                    b.ToTable("DriverEarnings");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EarningsUpdateEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("PushNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("SystemAlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("TripAssignedEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("TripOfferEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DriverPublicId")
                        .IsUnique();

                    b.ToTable("DriverNotificationPreferences");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverOfferHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TripOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TripOfferId");

                    b.HasIndex("DriverId", "TimestampUtc");

                    b.ToTable("DriverOfferHistories");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverPrivacySetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowAnalyticsTracking")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConsentGivenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DataRetentionConsentGiven")
                        .HasColumnType("bit");

                    b.Property<Guid>("DriverPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ShareLocationWithDispatcher")
                        .HasColumnType("bit");

                    b.Property<bool>("ShareTripHistoryWithThirdParties")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DriverPublicId")
                        .IsUnique();

                    b.ToTable("DriverPrivacySettings");
                });

            modelBuilder.Entity("TruckMate.Core.Models.LegalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Type", "IsActive");

                    b.ToTable("LegalDocuments");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShipmentRequestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("ShipmentRequestId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("TruckMate.Core.Models.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeleteRequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPasswordChangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneVerified")
                        .HasColumnType("bit");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledHardDeleteAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("TraderId")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TraderId");

                    b.HasIndex("TripId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TruckMate.Core.Models.ShipmentRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedDriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FinalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRefrigerated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReturnTrip")
                        .HasColumnType("bit");

                    b.Property<double?>("MaxTemperature")
                        .HasColumnType("float");

                    b.Property<double?>("MinTemperature")
                        .HasColumnType("float");

                    b.Property<string>("OriginCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("ScheduledTime")
                        .HasColumnType("time");

                    b.Property<string>("ShipmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TraderId")
                        .HasColumnType("int");

                    b.Property<string>("TruckType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDriverId");

                    b.HasIndex("TraderId");

                    b.ToTable("ShipmentRequests");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Trader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteRequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmailVerificationOtpExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailVerificationOtpHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PhoneVerificationOtpExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneVerificationOtpHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ScheduledHardDeleteAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("TruckMate.Core.Models.TraderAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("PerformedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TraderPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("TraderPublicId");

                    b.ToTable("TraderAuditLogs");
                });

            modelBuilder.Entity("TruckMate.Core.Models.TraderNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("InvoiceGenerated")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentFailed")
                        .HasColumnType("bit");

                    b.Property<bool>("PushNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipmentAssignedToDriver")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipmentCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipmentCreatedConfirmation")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipmentDelayed")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipmentDelivered")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipmentInTransit")
                        .HasColumnType("bit");

                    b.Property<bool>("ShipmentPickedUp")
                        .HasColumnType("bit");

                    b.Property<bool>("SmsNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("TraderPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TraderPublicId")
                        .IsUnique();

                    b.ToTable("TraderNotificationPreferences");
                });

            modelBuilder.Entity("TruckMate.Core.Models.TraderPrivacySetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowAnalyticsTracking")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowMarketingCommunications")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ConsentGivenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DataRetentionConsentGiven")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GdprDataExportDeliveredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GdprDataExportRequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ShareBusinessDataWithPartners")
                        .HasColumnType("bit");

                    b.Property<bool>("ShareShipmentDataForResearch")
                        .HasColumnType("bit");

                    b.Property<Guid>("TraderPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TraderPublicId")
                        .IsUnique();

                    b.ToTable("TraderPrivacySettings");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<int>("ShipmentRequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("OfferId");

                    b.HasIndex("ShipmentRequestId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TruckMate.Core.Models.TripOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OfferedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DriverId", "Status");

                    b.HasIndex("ExpiresAtUtc", "Status");

                    b.HasIndex("TripId", "Status");

                    b.ToTable("TripOffers");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("plateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("trucks");
                });

            modelBuilder.Entity("TruckMate.Core.Models.CourierShipment", b =>
                {
                    b.HasOne("TruckMate.Core.Models.DeliveryTrip", "Trip")
                        .WithOne("CourierShipment")
                        .HasForeignKey("TruckMate.Core.Models.CourierShipment", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DeliveryTrip", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "AssignedDriver")
                        .WithMany()
                        .HasForeignKey("AssignedDriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TruckMate.Core.Models.Trader", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedDriver");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Driver", b =>
                {
                    b.HasOne("TruckMate.Core.Models.DeliveryTrip", "AssignedDeliveryTrip")
                        .WithMany()
                        .HasForeignKey("AssignedDeliveryTripId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TruckMate.Core.Models.People", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDeliveryTrip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverAuditLog", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverPublicId")
                        .HasPrincipalKey("PublicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverDailySummary", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverEarning", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .HasPrincipalKey("PublicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruckMate.Core.Models.DeliveryTrip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverNotificationPreference", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverPublicId")
                        .HasPrincipalKey("PublicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverOfferHistory", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruckMate.Core.Models.TripOffer", "TripOffer")
                        .WithMany()
                        .HasForeignKey("TripOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("TripOffer");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DriverPrivacySetting", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverPublicId")
                        .HasPrincipalKey("PublicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Offer", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckMate.Core.Models.ShipmentRequest", "ShipmentRequest")
                        .WithMany("Offers")
                        .HasForeignKey("ShipmentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("ShipmentRequest");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Review", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckMate.Core.Models.Trader", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckMate.Core.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Trader");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TruckMate.Core.Models.ShipmentRequest", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "AssignedDriver")
                        .WithMany()
                        .HasForeignKey("AssignedDriverId");

                    b.HasOne("TruckMate.Core.Models.Trader", "Trader")
                        .WithMany("Shipments")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDriver");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Trader", b =>
                {
                    b.HasOne("TruckMate.Core.Models.People", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TruckMate.Core.Models.TraderAuditLog", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Trader", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderPublicId")
                        .HasPrincipalKey("PublicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("TruckMate.Core.Models.TraderNotificationPreference", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Trader", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderPublicId")
                        .HasPrincipalKey("PublicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("TruckMate.Core.Models.TraderPrivacySetting", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Trader", "Trader")
                        .WithMany()
                        .HasForeignKey("TraderPublicId")
                        .HasPrincipalKey("PublicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Trip", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckMate.Core.Models.Offer", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckMate.Core.Models.ShipmentRequest", "ShipmentRequest")
                        .WithMany()
                        .HasForeignKey("ShipmentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Offer");

                    b.Navigation("ShipmentRequest");
                });

            modelBuilder.Entity("TruckMate.Core.Models.TripOffer", b =>
                {
                    b.HasOne("TruckMate.Core.Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TruckMate.Core.Models.DeliveryTrip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TruckMate.Core.Models.DeliveryTrip", b =>
                {
                    b.Navigation("CourierShipment");
                });

            modelBuilder.Entity("TruckMate.Core.Models.ShipmentRequest", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("TruckMate.Core.Models.Trader", b =>
                {
                    b.Navigation("Shipments");
                });
#pragma warning restore 612, 618
        }
    }
}
